global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: dgdn-api
  metrics_path: /metrics
  scrape_interval: 10s
  static_configs:
  - targets:
    - dgdn-api:8000
- job_name: redis
  static_configs:
  - targets:
    - redis:6379
