apiVersion: v1
kind: Service
metadata:
  name: dgdn-service-service
  labels:
    app: dgdn-service
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: dgdn-service
